### PR TITLE
Deprecation notice

### LINKED ISSUE #23: Google has announced a Google Photos API
More info:
- https://developers.googleblog.com/2018/05/introducing-google-photos-partner.html
- https://developers.google.com/photos/

Maybe that could help this project.

Or possibly merge with rclone (https://forum.rclone.org/t/google-photos-api/5593/10)?

### PR DESCRIPTION
**Pull request by nmrshll**
closes #23

### CODE REVIEW

**Comment by ammgws** [comment]
Last time I checked all uploads made through the API count toward your storage quota. Is that no longer the case?

**Comment by nmrshll** [comment]
It is still the case according to the docs:

> Note: All media items uploaded to Google Photos through the API are stored in full resolution at original quality. If your uploads exceed 25MB per user, your application should remind the user that these uploads will count towards storage in their Google Account.

Luckily since it's only for files over 25MB we can easily work around the limitation by resizing files on the client side. That functionality is not included in the official google go library (neither is upload, by the way), but I've been working on a more complete google photos client library and uploader, and we could make it an option to resize any files over 25MB before upload.
Here's the projects I'm talking about:
https://github.com/nmrshll/gphotos-uploader-cli
https://github.com/nmrshll/google-photos-api-client-go

**Comment by ammgws** [comment]
In that case I wouldn't say this project is depracated. It's not only photos - videos would also have to be resized. Big difference between having to do that on the client side versus Google server side as it is now.

**Comment by nmrshll** [comment]
Fair point.
There is work ahead for making local transcoding happen on the client side. I'll start researching if there is info on the exact transcoding parameters that Google uses, and research golang media transcoding libraries available to see if we could include that transparently in the Google photos client lib I'm working on.
Any help from contributors to this repo is welcome !

**Comment by simonedegiacomi** [comment]
@ammgws what do you think about the solution that we talked about on the issue #23? That would mean to deprecate this project adding a note that says to still use this project if you need the compression to now.

**Comment by nmrshll** [comment]
I think he has a point in not deprecating it just yet.

Maybe let's add one note on each project:
- on the newer CLI uploader / api library: saying that big files count
towards paid storage and that there is another library to get around that
- on the older repo: saying that we plan to deprecate it once we've sorted
out the compression problem, and point to the newer repos in the works.
(just to warn people from building on top of something we plan to deprecate
one day)

Le lun. 3 sept. 2018 à 11:13, Simone Degiacomi <notifications@github.com> a
écrit :

**Comment by simonedegiacomi** [comment]
Ok, let's do like this.

**Pull request merged**
