### PR TITLE
Bug fix and Album sharing capability

### PR DESCRIPTION
**Pull request by GaPhi**
To be merged after review...

### CODE REVIEW

**Comment by simonedegiacomi** [comment]
Thank you for the pull request!
I hope to review it tomorrow, I'll write here if I have any question :-)

**Comment by simonedegiacomi** [comment]
Thank you Philippe for the race condition fix, that was an hard to find bug!

Regarding the capability to share an album with another user: if I understood it correctly, this is a one-time operation for each user you want to share the album with, right?

I have in mind some scenarios in which this feature can be useful, but I think that they are very specific and not needed for the general user of this tool. Can you please share what scenarios you thought about?

Since the library is built upon undocumented behaviors of Google servers, I would like to keep the code that calls the "API" as short as possible, since it may break at any point of time. However, I think it's worth to take the risk of breaks if the feature can become handy also for general users of the tool :-)

**Comment by GaPhi** [comment]
You are right for the user sharing operation. It should be done at least
once.

My use case is the following (very specific).

I have several IP cameras connected to a raspberry-like for motion
detection.
On moving, I generate a video file.

This generated between 1500 to 3500 video files a day (10 to 30GB of data a
day), depending on the wind (branches moves and triggers the recording).

Thus, with a single Google account, I exceed the upload quota and need a
second account (maybe more...). But I want to have all videos available
from anywhere and anytime in a single album for each day.

Then I create a new album for the first video of a day, upload the
following in same album and, if there is an upload error, I share the album
with another account only once before uploading to the shared album with
the other account. And so one.

I had some rare case where a file was to upload but the tool did not start.
It took me about 10min to find the race condition.

I works now perfectly and already helped solving robbery in the
neighborhood... The police loves my system!

I just share the adjustments made to your tool if it makes sense to you, I
have my own development branch anyway...

Best regards,

Philippe

**Comment by simonedegiacomi** [comment]
Thank you for the explanation and nice project!

For the moment I would like to integrate only the changes to fix the race condition, and in the future, if other users ask for the functionality, I would like also to integrate the feature. What do you think?

**Comment by GaPhi** [comment]
It is your project... You choose.

As written, I will keep this feature on my branch as I need it.

**Comment by simonedegiacomi** [comment]
I cherry-picked the commit and pushed to master, thank you again for the fix!

I'll close the PR for now, but anyone should be able to comment here if needed

**Pull request closed without merging**
